eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul

ribbon:
  ConnectTimeOut: 10000
  ReadTimeOut: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      service-id: service-ribbon
    api-feign:
      path: /api-feign/**
      service-id: service-feign

  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

