spring:
  cloud:
    gateway:
      routes:
      - id: elapsed-route
        uri: http://httpbin.org:80/get
        filters:
        - RequestTime=true
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: elapsed-route
