spring:
  cloud:
    gateway:
      routes:
      - id: limit-route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
  profiles: limit-route
  redis:
    host: 47.101.44.123
    port: 6379
    database: 0
