spring:
  cloud:
    gateway:
      routes:
      - id: add-request-header-route
        uri: http://httpbin.org:80/get
        filters:
        - AddRequestHeader=X-Request-Bar, Bar
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add-request-header-route